# Generated by Django 3.2.14 on 2022-08-03 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coffee',
            name='coffee_content',
            field=models.TextField(max_length=300, null=True),
        ),
    ]
