# Generated by Django 3.2.14 on 2022-08-03 12:29

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('coffee', '0002_coffee_coffee_content'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Coffee',
            new_name='Coffees',
        ),
    ]
