# Generated by Django 3.2.14 on 2022-08-03 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0005_coffeepost'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Coffees',
        ),
    ]
