# Generated by Django 3.2.14 on 2022-08-28 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0009_auto_20220824_2210'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_on']},
        ),
        migrations.AlterField(
            model_name='coffeepost',
            name='coffee_brand',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='coffeepost',
            name='coffee_name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='coffeepost',
            name='coffee_origin',
            field=models.CharField(max_length=20),
        ),
    ]
